package com.eagle.futbolapi.features.base.annotation;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Annotation to mark fields that are automatically generated by the system.
 * Fields marked with this annotation cannot be modified via DTO updates or patches.
 * Typically used for computed or auto-generated values like unique keys.
 */
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
public @interface GeneratedField {

  /**
   * Optional message to display when modification is attempted.
   *
   * @return the error message
   */
  String message() default "This field is auto-generated and cannot be modified";
}
