INSERT INTO country (co_id, co_name, co_code, co_iso_code, co_display_name, co_flag_url, co_created_at, co_created_by)
VALUES
  (1, 'United Mexican States', 'MX', 'MEX', 'Mexico', 'https://flagcdn.com/mx.svg', NOW(), 'admin'),
  (2, 'Japan', 'JP', 'JPN', 'Japan', 'https://flagcdn.com/jp.svg', NOW(), 'admin'),
  (3, 'Federative Republic of Brazil', 'BR', 'BRA', 'Brazil', 'https://flagcdn.com/br.svg', NOW(), 'admin'),
  (4, 'Federal Republic of Germany', 'DE', 'DEU', 'Germany', 'https://flagcdn.com/de.svg', NOW(), 'admin'),
  (5, 'French Republic', 'FR', 'FRA', 'France', 'https://flagcdn.com/fr.svg', NOW(), 'admin'),
  (6, 'Kingdom of Spain', 'ES', 'ESP', 'Spain', 'https://flagcdn.com/es.svg', NOW(), 'admin'),
  (7, 'England', 'GB', 'ENG', 'England', 'https://flagcdn.com/gb-eng.svg', NOW(), 'admin'),
  (8, 'Italian Republic', 'IT', 'ITA', 'Italy', 'https://flagcdn.com/it.svg', NOW(), 'admin'),
  (9, 'United States of America', 'US', 'USA', 'United States', 'https://flagcdn.com/us.svg', NOW(), 'admin'),
  (10, 'Kingdom of the Netherlands', 'NL', 'NLD', 'Netherlands', 'https://flagcdn.com/nl.svg', NOW(), 'admin'),
  (11, 'Commonwealth of Australia', 'AU', 'AUS', 'Australia', 'https://flagcdn.com/au.svg', NOW(), 'admin'),
  (12, 'Canada', 'CA', 'CAN', 'Canada', 'https://flagcdn.com/ca.svg', NOW(), 'admin'),
  (13, 'Oriental Republic of Uruguay', 'UY', 'URY', 'Uruguay', 'https://flagcdn.com/uy.svg', NOW(), 'admin'),
  (14, 'Republic of Chile', 'CL', 'CHL', 'Chile', 'https://flagcdn.com/cl.svg', NOW(), 'admin'),
  (15, 'Republic of Colombia', 'CO', 'COL', 'Colombia', 'https://flagcdn.com/co.svg', NOW(), 'admin'),
  (16, 'Republic of Peru', 'PE', 'PER', 'Peru', 'https://flagcdn.com/pe.svg', NOW(), 'admin'),
  (17, 'Bolivarian Republic of Venezuela', 'VE', 'VEN', 'Venezuela', 'https://flagcdn.com/ve.svg', NOW(), 'admin'),
  (18, 'Republic of South Africa', 'ZA', 'ZAF', 'South Africa', 'https://flagcdn.com/za.svg', NOW(), 'admin'),
  (19, 'New Zealand', 'NZ', 'NZL', 'New Zealand', 'https://flagcdn.com/nz.svg', NOW(), 'admin'),
  (20, 'Ireland', 'IE', 'IRL', 'Ireland', 'https://flagcdn.com/ie.svg', NOW(), 'admin'),
  (21, 'Kingdom of Sweden', 'SE', 'SWE', 'Sweden', 'https://flagcdn.com/se.svg', NOW(), 'admin'),
  (22, 'Federal Republic of Nigeria', 'NG', 'NGA', 'Nigeria', 'https://flagcdn.com/ng.svg', NOW(), 'admin'),
  (23, 'Arab Republic of Egypt', 'EG', 'EGY', 'Egypt', 'https://flagcdn.com/eg.svg', NOW(), 'admin'),
  (24, 'Kingdom of Saudi Arabia', 'SA', 'SAU', 'Saudi Arabia', 'https://flagcdn.com/sa.svg', NOW(), 'admin'),
  (25, 'United Arab Emirates', 'AE', 'ARE', 'United Arab Emirates', 'https://flagcdn.com/ae.svg', NOW(), 'admin'),
  (26, 'Argentine Republic', 'AR', 'ARG', 'Argentina', 'https://flagcdn.com/ar.svg', NOW(), 'admin');
