-- H2 SQL insert script for Team (Professional and youth teams from clubs)
-- Creates men's, women's, and U20 teams for each club organization
INSERT INTO team (tm_id, tm_name, tm_display_name, tm_code, tm_gender, tm_age_category, tm_founded, organization_id, country_id, venue_id, tm_logo, tm_primary_color, tm_secondary_color, tm_website, tm_active, tm_created_at, tm_created_by)
VALUES
  -- Mexican Clubs
  (1, 'Club América Men''s Team', 'América Men', 'AME', 'MALE', 'PROFESSIONAL', '1916-10-12', 35, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/10/Club_America_crest.png', '#F5CE09', '#002255', 'https://www.clubamerica.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (2, 'Club América Women''s Team', 'América Women', 'AME', 'FEMALE', 'PROFESSIONAL', '1916-10-12', 35, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/10/Club_America_crest.png', '#F5CE09', '#002255', 'https://www.clubamerica.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (3, 'Club América U20', 'América U20', 'AMU', 'MALE', 'U20', '1916-10-12', 35, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/10/Club_America_crest.png', '#F5CE09', '#002255', 'https://www.clubamerica.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (4, 'Tigres UANL Men''s Team', 'Tigres Men', 'TIG', 'MALE', 'PROFESSIONAL', '1960-03-07', 36, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/13/Tigres_UANL_logo.svg', '#F7B801', '#002D56', 'https://www.tigres.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (5, 'Tigres UANL Women''s Team', 'Tigres Women', 'TIG', 'FEMALE', 'PROFESSIONAL', '1960-03-07', 36, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/13/Tigres_UANL_logo.svg', '#F7B801', '#002D56', 'https://www.tigres.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (6, 'Tigres UANL U20', 'Tigres U20', 'TIU', 'MALE', 'U20', '1960-03-07', 36, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/13/Tigres_UANL_logo.svg', '#F7B801', '#002D56', 'https://www.tigres.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (7, 'Cruz Azul Men''s Team', 'Cruz Azul Men', 'CAZ', 'MALE', 'PROFESSIONAL', '1927-05-22', 37, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2b/Cruz_Azul_FC_logo.svg', '#0070BD', '#FFFFFF', 'https://www.cruzazulfc.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (8, 'Cruz Azul Women''s Team', 'Cruz Azul Women', 'CAZ', 'FEMALE', 'PROFESSIONAL', '1927-05-22', 37, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2b/Cruz_Azul_FC_logo.svg', '#0070BD', '#FFFFFF', 'https://www.cruzazulfc.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (9, 'Cruz Azul U20', 'Cruz Azul U20', 'CAU', 'MALE', 'U20', '1927-05-22', 37, 1, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2b/Cruz_Azul_FC_logo.svg', '#0070BD', '#FFFFFF', 'https://www.cruzazulfc.com.mx', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- Brazilian Clubs
  (10, 'Flamengo Men''s Team', 'Flamengo Men', 'FLA', 'MALE', 'PROFESSIONAL', '1895-11-17', 38, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/7b/Flamengo_braz_logo.svg', '#E31E24', '#000000', 'https://www.flamengo.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (11, 'Flamengo Women''s Team', 'Flamengo Women', 'FLA', 'FEMALE', 'PROFESSIONAL', '1895-11-17', 38, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/7b/Flamengo_braz_logo.svg', '#E31E24', '#000000', 'https://www.flamengo.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (12, 'Flamengo U20', 'Flamengo U20', 'FLU', 'MALE', 'U20', '1895-11-17', 38, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/7b/Flamengo_braz_logo.svg', '#E31E24', '#000000', 'https://www.flamengo.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (13, 'Palmeiras Men''s Team', 'Palmeiras Men', 'PAL', 'MALE', 'PROFESSIONAL', '1914-08-26', 39, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/5c/Palmeiras_logo.svg', '#046A38', '#FFFFFF', 'https://www.palmeiras.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (14, 'Palmeiras Women''s Team', 'Palmeiras Women', 'PAL', 'FEMALE', 'PROFESSIONAL', '1914-08-26', 39, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/5c/Palmeiras_logo.svg', '#046A38', '#FFFFFF', 'https://www.palmeiras.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (15, 'Palmeiras U20', 'Palmeiras U20', 'PAU', 'MALE', 'U20', '1914-08-26', 39, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/5c/Palmeiras_logo.svg', '#046A38', '#FFFFFF', 'https://www.palmeiras.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (16, 'Corinthians Men''s Team', 'Corinthians Men', 'COR', 'MALE', 'PROFESSIONAL', '1910-09-01', 40, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/9/93/SC_Corinthians_Paulista_crest.svg', '#000000', '#FFFFFF', 'https://www.corinthians.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (17, 'Corinthians Women''s Team', 'Corinthians Women', 'COR', 'FEMALE', 'PROFESSIONAL', '1910-09-01', 40, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/9/93/SC_Corinthians_Paulista_crest.svg', '#000000', '#FFFFFF', 'https://www.corinthians.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (18, 'Corinthians U20', 'Corinthians U20', 'COU', 'MALE', 'U20', '1910-09-01', 40, 3, NULL, 'https://upload.wikimedia.org/wikipedia/en/9/93/SC_Corinthians_Paulista_crest.svg', '#000000', '#FFFFFF', 'https://www.corinthians.com.br', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- Japanese Clubs  
  (19, 'Urawa Red Diamonds Men''s Team', 'Urawa Men', 'URW', 'MALE', 'PROFESSIONAL', '1950-01-01', 41, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/71/Urawa_Red_Diamonds_logo.svg', '#E60012', '#000000', 'https://www.urawa-reds.co.jp', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (20, 'Urawa Red Diamonds Women''s Team', 'Urawa Women', 'URW', 'FEMALE', 'PROFESSIONAL', '1950-01-01', 41, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/71/Urawa_Red_Diamonds_logo.svg', '#E60012', '#000000', 'https://www.urawa-reds.co.jp', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (21, 'Urawa Red Diamonds U20', 'Urawa U20', 'URU', 'MALE', 'U20', '1950-01-01', 41, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/71/Urawa_Red_Diamonds_logo.svg', '#E60012', '#000000', 'https://www.urawa-reds.co.jp', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (22, 'Kashima Antlers Men''s Team', 'Kashima Men', 'KAS', 'MALE', 'PROFESSIONAL', '1947-01-01', 42, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2d/Kashima_Antlers_logo.svg', '#DC0017', '#000C5C', 'https://www.antlers.co.jp', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (23, 'Kashima Antlers Women''s Team', 'Kashima Women', 'KAS', 'FEMALE', 'PROFESSIONAL', '1947-01-01', 42, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2d/Kashima_Antlers_logo.svg', '#DC0017', '#000C5C', 'https://www.antlers.co.jp', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (24, 'Kashima Antlers U20', 'Kashima U20', 'KAU', 'MALE', 'U20', '1947-01-01', 42, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2d/Kashima_Antlers_logo.svg', '#DC0017', '#000C5C', 'https://www.antlers.co.jp', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (25, 'Yokohama F. Marinos Men''s Team', 'Yokohama Men', 'YFM', 'MALE', 'PROFESSIONAL', '1972-01-01', 43, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/6/65/Yokohama_F._Marinos_logo.svg', '#001489', '#E1171F', 'https://www.f-marinos.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (26, 'Yokohama F. Marinos Women''s Team', 'Yokohama Women', 'YFM', 'FEMALE', 'PROFESSIONAL', '1972-01-01', 43, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/6/65/Yokohama_F._Marinos_logo.svg', '#001489', '#E1171F', 'https://www.f-marinos.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (27, 'Yokohama F. Marinos U20', 'Yokohama U20', 'YFU', 'MALE', 'U20', '1972-01-01', 43, 2, NULL, 'https://upload.wikimedia.org/wikipedia/en/6/65/Yokohama_F._Marinos_logo.svg', '#001489', '#E1171F', 'https://www.f-marinos.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- German Clubs
  (28, 'Bayern Munich Men''s Team', 'Bayern Men', 'FCB', 'MALE', 'PROFESSIONAL', '1900-02-27', 44, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_München_logo_%282017%29.svg', '#DC052D', '#0066B2', 'https://fcbayern.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (29, 'Bayern Munich Women''s Team', 'Bayern Women', 'FCB', 'FEMALE', 'PROFESSIONAL', '1900-02-27', 44, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_München_logo_%282017%29.svg', '#DC052D', '#0066B2', 'https://fcbayern.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (30, 'Bayern Munich U20', 'Bayern U20', 'FCU', 'MALE', 'U20', '1900-02-27', 44, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_München_logo_%282017%29.svg', '#DC052D', '#0066B2', 'https://fcbayern.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (31, 'Borussia Dortmund Men''s Team', 'Dortmund Men', 'BVB', 'MALE', 'PROFESSIONAL', '1909-12-19', 45, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/3/33/Borussia_Dortmund_logo.svg', '#FDE100', '#000000', 'https://www.bvb.de', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (32, 'Borussia Dortmund Women''s Team', 'Dortmund Women', 'BVB', 'FEMALE', 'PROFESSIONAL', '1909-12-19', 45, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/3/33/Borussia_Dortmund_logo.svg', '#FDE100', '#000000', 'https://www.bvb.de', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (33, 'Borussia Dortmund U20', 'Dortmund U20', 'BVU', 'MALE', 'U20', '1909-12-19', 45, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/3/33/Borussia_Dortmund_logo.svg', '#FDE100', '#000000', 'https://www.bvb.de', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (34, 'Bayer Leverkusen Men''s Team', 'Leverkusen Men', 'B04', 'MALE', 'PROFESSIONAL', '1904-07-01', 46, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg', '#E32221', '#000000', 'https://www.bayer04.de', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (35, 'Bayer Leverkusen Women''s Team', 'Leverkusen Women', 'B04', 'FEMALE', 'PROFESSIONAL', '1904-07-01', 46, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg', '#E32221', '#000000', 'https://www.bayer04.de', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (36, 'Bayer Leverkusen U20', 'Leverkusen U20', 'B0U', 'MALE', 'U20', '1904-07-01', 46, 4, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg', '#E32221', '#000000', 'https://www.bayer04.de', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- French Clubs
  (37, 'Paris Saint-Germain Men''s Team', 'PSG Men', 'PSG', 'MALE', 'PROFESSIONAL', '1970-08-12', 47, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg', '#004170', '#DA291C', 'https://www.psg.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (38, 'Paris Saint-Germain Women''s Team', 'PSG Women', 'PSG', 'FEMALE', 'PROFESSIONAL', '1970-08-12', 47, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg', '#004170', '#DA291C', 'https://www.psg.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (39, 'Paris Saint-Germain U20', 'PSG U20', 'PSU', 'MALE', 'U20', '1970-08-12', 47, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg', '#004170', '#DA291C', 'https://www.psg.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (40, 'Olympique de Marseille Men''s Team', 'Marseille Men', 'OMR', 'MALE', 'PROFESSIONAL', '1899-08-31', 48, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/8/8c/Olympique_de_Marseille_logo.svg', '#2FAEE0', '#FFFFFF', 'https://www.om.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (41, 'Olympique de Marseille Women''s Team', 'Marseille Women', 'OMR', 'FEMALE', 'PROFESSIONAL', '1899-08-31', 48, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/8/8c/Olympique_de_Marseille_logo.svg', '#2FAEE0', '#FFFFFF', 'https://www.om.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (42, 'Olympique de Marseille U20', 'Marseille U20', 'OMU', 'MALE', 'U20', '1899-08-31', 48, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/8/8c/Olympique_de_Marseille_logo.svg', '#2FAEE0', '#FFFFFF', 'https://www.om.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (43, 'Olympique Lyonnais Men''s Team', 'Lyon Men', 'OLY', 'MALE', 'PROFESSIONAL', '1950-08-03', 49, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/Olympique_lyonnais_logo.svg', '#DA0812', '#003668', 'https://www.ol.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (44, 'Olympique Lyonnais Women''s Team', 'Lyon Women', 'OLY', 'FEMALE', 'PROFESSIONAL', '1950-08-03', 49, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/Olympique_lyonnais_logo.svg', '#DA0812', '#003668', 'https://www.ol.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (45, 'Olympique Lyonnais U20', 'Lyon U20', 'OLU', 'MALE', 'U20', '1950-08-03', 49, 5, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/Olympique_lyonnais_logo.svg', '#DA0812', '#003668', 'https://www.ol.fr', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- Spanish Clubs
  (46, 'Real Madrid Men''s Team', 'Real Madrid Men', 'RMA', 'MALE', 'PROFESSIONAL', '1902-03-06', 50, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', '#FEBE10', '#00529F', 'https://www.realmadrid.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (47, 'Real Madrid Women''s Team', 'Real Madrid Women', 'RMA', 'FEMALE', 'PROFESSIONAL', '1902-03-06', 50, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', '#FEBE10', '#00529F', 'https://www.realmadrid.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (48, 'Real Madrid U20', 'Real Madrid U20', 'RMU', 'MALE', 'U20', '1902-03-06', 50, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', '#FEBE10', '#00529F', 'https://www.realmadrid.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (49, 'FC Barcelona Men''s Team', 'Barcelona Men', 'BAR', 'MALE', 'PROFESSIONAL', '1899-11-29', 51, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', '#A50044', '#004D98', 'https://www.fcbarcelona.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (50, 'FC Barcelona Women''s Team', 'Barcelona Women', 'BAR', 'FEMALE', 'PROFESSIONAL', '1899-11-29', 51, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', '#A50044', '#004D98', 'https://www.fcbarcelona.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (51, 'FC Barcelona U20', 'Barcelona U20', 'BRU', 'MALE', 'U20', '1899-11-29', 51, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', '#A50044', '#004D98', 'https://www.fcbarcelona.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (52, 'Atletico Madrid Men''s Team', 'Atlético Men', 'ATM', 'MALE', 'PROFESSIONAL', '1903-04-26', 52, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg', '#CB3524', '#152E70', 'https://www.atleticodemadrid.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (53, 'Atletico Madrid Women''s Team', 'Atlético Women', 'ATM', 'FEMALE', 'PROFESSIONAL', '1903-04-26', 52, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg', '#CB3524', '#152E70', 'https://www.atleticodemadrid.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (54, 'Atletico Madrid U20', 'Atlético U20', 'ATU', 'MALE', 'U20', '1903-04-26', 52, 6, NULL, 'https://upload.wikimedia.org/wikipedia/en/f/f4/Atletico_Madrid_2017_logo.svg', '#CB3524', '#152E70', 'https://www.atleticodemadrid.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- English Clubs
  (55, 'Manchester United Men''s Team', 'Man United Men', 'MUN', 'MALE', 'PROFESSIONAL', '1878-01-01', 53, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', '#DA291C', '#FBE122', 'https://www.manutd.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (56, 'Manchester United Women''s Team', 'Man United Women', 'MUN', 'FEMALE', 'PROFESSIONAL', '1878-01-01', 53, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', '#DA291C', '#FBE122', 'https://www.manutd.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (57, 'Manchester United U20', 'Man United U20', 'MUU', 'MALE', 'U20', '1878-01-01', 53, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', '#DA291C', '#FBE122', 'https://www.manutd.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (58, 'Liverpool Men''s Team', 'Liverpool Men', 'LIV', 'MALE', 'PROFESSIONAL', '1892-06-03', 54, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg', '#C8102E', '#00B2A9', 'https://www.liverpoolfc.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (59, 'Liverpool Women''s Team', 'Liverpool Women', 'LIV', 'FEMALE', 'PROFESSIONAL', '1892-06-03', 54, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg', '#C8102E', '#00B2A9', 'https://www.liverpoolfc.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (60, 'Liverpool U20', 'Liverpool U20', 'LIU', 'MALE', 'U20', '1892-06-03', 54, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg', '#C8102E', '#00B2A9', 'https://www.liverpoolfc.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (61, 'Arsenal Men''s Team', 'Arsenal Men', 'ARS', 'MALE', 'PROFESSIONAL', '1886-10-01', 55, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg', '#EF0107', '#FFFFFF', 'https://www.arsenal.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (62, 'Arsenal Women''s Team', 'Arsenal Women', 'ARS', 'FEMALE', 'PROFESSIONAL', '1886-10-01', 55, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg', '#EF0107', '#FFFFFF', 'https://www.arsenal.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (63, 'Arsenal U20', 'Arsenal U20', 'ARU', 'MALE', 'U20', '1886-10-01', 55, 7, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg', '#EF0107', '#FFFFFF', 'https://www.arsenal.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- Italian Clubs
  (64, 'Juventus Men''s Team', 'Juventus Men', 'JUV', 'MALE', 'PROFESSIONAL', '1897-11-01', 56, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/15/Juventus_FC_2017_logo.svg', '#000000', '#FFFFFF', 'https://www.juventus.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (65, 'Juventus Women''s Team', 'Juventus Women', 'JUV', 'FEMALE', 'PROFESSIONAL', '1897-11-01', 56, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/15/Juventus_FC_2017_logo.svg', '#000000', '#FFFFFF', 'https://www.juventus.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (66, 'Juventus U20', 'Juventus U20', 'JUU', 'MALE', 'U20', '1897-11-01', 56, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/1/15/Juventus_FC_2017_logo.svg', '#000000', '#FFFFFF', 'https://www.juventus.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (67, 'AC Milan Men''s Team', 'Milan Men', 'ACM', 'MALE', 'PROFESSIONAL', '1899-12-16', 57, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/d/d0/AC_Milan_logo.svg', '#FB090B', '#000000', 'https://www.acmilan.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (68, 'AC Milan Women''s Team', 'Milan Women', 'ACM', 'FEMALE', 'PROFESSIONAL', '1899-12-16', 57, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/d/d0/AC_Milan_logo.svg', '#FB090B', '#000000', 'https://www.acmilan.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (69, 'AC Milan U20', 'Milan U20', 'ACU', 'MALE', 'U20', '1899-12-16', 57, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/d/d0/AC_Milan_logo.svg', '#FB090B', '#000000', 'https://www.acmilan.com', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (70, 'Inter Milan Men''s Team', 'Inter Men', 'INT', 'MALE', 'PROFESSIONAL', '1908-03-09', 58, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/Inter_Milan_logo.svg', '#010E80', '#000000', 'https://www.inter.it', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (71, 'Inter Milan Women''s Team', 'Inter Women', 'INT', 'FEMALE', 'PROFESSIONAL', '1908-03-09', 58, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/Inter_Milan_logo.svg', '#010E80', '#000000', 'https://www.inter.it', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (72, 'Inter Milan U20', 'Inter U20', 'INU', 'MALE', 'U20', '1908-03-09', 58, 8, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/Inter_Milan_logo.svg', '#010E80', '#000000', 'https://www.inter.it', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- Dutch Clubs
  (73, 'Ajax Men''s Team', 'Ajax Men', 'AJX', 'MALE', 'PROFESSIONAL', '1900-03-18', 59, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg', '#D2122E', '#FFFFFF', 'https://www.ajax.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (74, 'Ajax Women''s Team', 'Ajax Women', 'AJX', 'FEMALE', 'PROFESSIONAL', '1900-03-18', 59, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg', '#D2122E', '#FFFFFF', 'https://www.ajax.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (75, 'Ajax U20', 'Ajax U20', 'AJU', 'MALE', 'U20', '1900-03-18', 59, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg', '#D2122E', '#FFFFFF', 'https://www.ajax.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (76, 'PSV Eindhoven Men''s Team', 'PSV Men', 'PSV', 'MALE', 'PROFESSIONAL', '1913-08-31', 60, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven_logo.svg', '#ED1C24', '#FFFFFF', 'https://www.psv.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (77, 'PSV Eindhoven Women''s Team', 'PSV Women', 'PSV', 'FEMALE', 'PROFESSIONAL', '1913-08-31', 60, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven_logo.svg', '#ED1C24', '#FFFFFF', 'https://www.psv.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (78, 'PSV Eindhoven U20', 'PSV U20', 'PEU', 'MALE', 'U20', '1913-08-31', 60, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/0/05/PSV_Eindhoven_logo.svg', '#ED1C24', '#FFFFFF', 'https://www.psv.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (79, 'Feyenoord Men''s Team', 'Feyenoord Men', 'FEY', 'MALE', 'PROFESSIONAL', '1908-07-19', 61, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/3/36/Feyenoord_logo.svg', '#E30613', '#000000', 'https://www.feyenoord.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (80, 'Feyenoord Women''s Team', 'Feyenoord Women', 'FEY', 'FEMALE', 'PROFESSIONAL', '1908-07-19', 61, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/3/36/Feyenoord_logo.svg', '#E30613', '#000000', 'https://www.feyenoord.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (81, 'Feyenoord U20', 'Feyenoord U20', 'FEU', 'MALE', 'U20', '1908-07-19', 61, 10, NULL, 'https://upload.wikimedia.org/wikipedia/en/3/36/Feyenoord_logo.svg', '#E30613', '#000000', 'https://www.feyenoord.nl', TRUE, CURRENT_TIMESTAMP, 'admin'),
  
  -- Swedish Clubs
  (82, 'Malmo FF Men''s Team', 'Malmö Men', 'MFF', 'MALE', 'PROFESSIONAL', '1910-02-24', 62, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2e/Malmo_FF_logo.svg', '#5DADE2', '#FFFFFF', 'https://www.mff.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (83, 'Malmo FF Women''s Team', 'Malmö Women', 'MFF', 'FEMALE', 'PROFESSIONAL', '1910-02-24', 62, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2e/Malmo_FF_logo.svg', '#5DADE2', '#FFFFFF', 'https://www.mff.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (84, 'Malmo FF U20', 'Malmö U20', 'MFU', 'MALE', 'U20', '1910-02-24', 62, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/2/2e/Malmo_FF_logo.svg', '#5DADE2', '#FFFFFF', 'https://www.mff.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (85, 'AIK Men''s Team', 'AIK Men', 'AIK', 'MALE', 'PROFESSIONAL', '1891-02-15', 63, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/5d/AIK_logo.svg', '#000000', '#FFCC00', 'https://www.aikfotboll.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (86, 'AIK Women''s Team', 'AIK Women', 'AIK', 'FEMALE', 'PROFESSIONAL', '1891-02-15', 63, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/5d/AIK_logo.svg', '#000000', '#FFCC00', 'https://www.aikfotboll.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (87, 'AIK U20', 'AIK U20', 'AIU', 'MALE', 'U20', '1891-02-15', 63, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/5/5d/AIK_logo.svg', '#000000', '#FFCC00', 'https://www.aikfotboll.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (88, 'Djurgardens IF Men''s Team', 'Djurgården Men', 'DIF', 'MALE', 'PROFESSIONAL', '1891-03-12', 64, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/f/f7/Djurgardens_IF_logo.svg', '#002D72', '#FFFFFF', 'https://www.dif.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (89, 'Djurgardens IF Women''s Team', 'Djurgården Women', 'DIF', 'FEMALE', 'PROFESSIONAL', '1891-03-12', 64, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/f/f7/Djurgardens_IF_logo.svg', '#002D72', '#FFFFFF', 'https://www.dif.se', TRUE, CURRENT_TIMESTAMP, 'admin'),
  (90, 'Djurgardens IF U20', 'Djurgården U20', 'DIU', 'MALE', 'U20', '1891-03-12', 64, 21, NULL, 'https://upload.wikimedia.org/wikipedia/en/f/f7/Djurgardens_IF_logo.svg', '#002D72', '#FFFFFF', 'https://www.dif.se', TRUE, CURRENT_TIMESTAMP, 'admin');
